#!/usr/bin/env python3

import argparse
import re
from pathlib import Path

import numpy as np

FLOAT_RE = re.compile(r"(?<![A-Za-z])[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")
TIMESTAMP_RE = re.compile(r"\[(\d+(?:\.\d+)?)\]")
STATE_PREFIX = "Updated state ="
FINAL_POINT_PREFIX = "Reached final reference point"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare a reference trajectory with real trajectory extracted from ROS 2 "
            "logs generated by ros2_px4_mpc_node (Updated state = ...)."
        )
    )
    parser.add_argument(
        "--ref",
        required=True,
        type=Path,
        help=(
            "Reference trajectory input: .npy/.csv/whitespace text with x y z columns, "
            "or a path_publisher ROS log containing '(x, y, z)' lines."
        ),
    )
    parser.add_argument(
        "--log",
        required=True,
        type=Path,
        help='ROS 2 log file containing lines with "Updated state = [...]".',
    )
    parser.add_argument(
        "--save-plot",
        type=Path,
        default=None,
        help="Optional output image path for 3D plot.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open interactive plot window.",
    )
    return parser.parse_args()


def _extract_floats(text: str) -> list[float]:
    normalized = re.sub(r"np\.float\d+\(", "(", text)
    return [float(v) for v in FLOAT_RE.findall(normalized)]


def parse_path_publisher_log_reference(path: Path) -> np.ndarray:
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    points = []

    for line in lines:
        if "Building path:" in line:
            continue

        # ROS 2 logger lines typically look like:
        # "... [path_publisher]: (x, y, z)"
        message = line.rsplit("]:", maxsplit=1)[-1]
        if "(" not in message or ")" not in message:
            continue

        tuple_text = message[message.find("(") : message.rfind(")") + 1]
        values = _extract_floats(tuple_text)
        if len(values) == 3:
            points.append(values)

    if len(points) < 2:
        raise ValueError(
            f'No path tuple points parsed from "{path}". '
            "Expected lines like '(x, y, z)' emitted by path_publisher."
        )

    return np.asarray(points, dtype=float)


def _normalize_reference_array(data: np.ndarray) -> np.ndarray:
    data = np.asarray(data, dtype=float)
    if data.ndim == 1:
        if data.size % 3 != 0:
            raise ValueError(
                f"1D reference input has {data.size} values, expected multiple of 3."
            )
        data = data.reshape(-1, 3)
    if data.ndim != 2 or data.shape[1] < 3:
        raise ValueError(
            f"Reference trajectory must be Nx3 (or NxM with M>=3), got {data.shape}."
        )
    return data[:, :3]


def load_reference_trajectory(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Reference trajectory file not found: {path}")

    if path.suffix.lower() == ".npy":
        return _normalize_reference_array(np.load(path))

    delimiter = "," if path.suffix.lower() == ".csv" else None
    try:
        return _normalize_reference_array(np.loadtxt(path, delimiter=delimiter))
    except ValueError:
        # For path_publisher ROS logs where path points are printed as tuples.
        return parse_path_publisher_log_reference(path)


def _extract_timestamp(line: str) -> float | None:
    matches = TIMESTAMP_RE.findall(line)
    if not matches:
        return None
    try:
        return float(matches[-1])
    except ValueError:
        return None


def parse_logged_states(log_path: Path) -> tuple[np.ndarray, np.ndarray | None]:
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")

    lines = log_path.read_text(encoding="utf-8", errors="ignore").splitlines()
    positions = []
    timestamps = []

    i = 0
    while i < len(lines):
        line = lines[i]
        if STATE_PREFIX not in line:
            i += 1
            continue

        ts = _extract_timestamp(line)
        state_chunk = line.split(STATE_PREFIX, maxsplit=1)[1]

        while "]" not in state_chunk and i + 1 < len(lines):
            i += 1
            state_chunk += " " + lines[i].strip()

        values = _extract_floats(state_chunk)
        if len(values) >= 3:
            positions.append(values[:3])
            timestamps.append(ts if ts is not None else np.nan)

        i += 1

    if not positions:
        raise ValueError(
            f'No states parsed from "{log_path}". Expected lines with "{STATE_PREFIX}".'
        )

    pos_arr = np.asarray(positions, dtype=float)
    ts_arr = np.asarray(timestamps, dtype=float)

    if np.all(np.isnan(ts_arr)):
        return pos_arr, None
    return pos_arr, ts_arr


def parse_final_point_timestamp(log_path: Path) -> float | None:
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")

    for line in log_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if FINAL_POINT_PREFIX not in line:
            continue

        timestamp = _extract_timestamp(line)
        if timestamp is not None:
            return timestamp

    return None


def compute_completion_time(
    state_timestamps: np.ndarray | None,
    final_point_timestamp: float | None,
) -> float | None:
    if state_timestamps is None or final_point_timestamp is None:
        return None

    valid_timestamps = state_timestamps[np.isfinite(state_timestamps)]
    if len(valid_timestamps) == 0:
        return None

    duration = final_point_timestamp - valid_timestamps[0]
    if duration < 0.0:
        return None

    return duration


def resample_trajectory(points, n_samples=1000):
    """
    Resample a 3D trajectory to n_samples points using arc length.
    points: array of shape (N, 3)
    """
    points = np.asarray(points)

    # Segment lengths
    segment_lengths = np.linalg.norm(np.diff(points, axis=0), axis=1)

    # Cumulative distance along trajectory
    cumulative = np.insert(np.cumsum(segment_lengths), 0, 0.0)

    total_length = cumulative[-1]

    if total_length == 0:
        return np.repeat(points[:1], n_samples, axis=0)

    # New equally spaced distances
    new_distances = np.linspace(0, total_length, n_samples)

    # Interpolate x, y, z independently
    resampled = np.column_stack([
        np.interp(new_distances, cumulative, points[:, dim])
        for dim in range(points.shape[1])
    ])

    return resampled

def compute_metrics(reference: np.ndarray, real: np.ndarray, n_samples=200) -> tuple[float, float]:
    a_resampled = resample_trajectory(reference, n_samples)
    b_resampled = resample_trajectory(real, n_samples)

    distances = np.linalg.norm(a_resampled - b_resampled, axis=1)
    return distances.mean(), distances.max()


def set_axes_equal(ax, points: np.ndarray) -> None:
    mins = np.min(points, axis=0)
    maxs = np.max(points, axis=0)
    centers = (mins + maxs) / 2.0
    max_range = np.max(maxs - mins)

    if max_range == 0.0:
        max_range = 1.0

    radius = max_range / 2.0
    ax.set_xlim(centers[0] - radius, centers[0] + radius)
    ax.set_ylim(centers[1] - radius, centers[1] + radius)
    ax.set_zlim(centers[2] - radius, centers[2] + radius)
    ax.set_box_aspect((1, 1, 1))


def plot_trajectories(
    reference: np.ndarray,
    real: np.ndarray,
    save_path: Path | None,
    show: bool,
) -> None:
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")

    ax.plot(
        reference[:, 1],
        reference[:, 0],
        -reference[:, 2],
        "--",
        linewidth=2.0,
    )
    ax.plot(
        real[:, 1],
        real[:, 0],
        -real[:, 2],
        linewidth=2.0,
    )

    plot_points = np.vstack(
        (
            np.column_stack((reference[:, 1], reference[:, 0], -reference[:, 2])),
            np.column_stack((real[:, 1], real[:, 0], -real[:, 2])),
        )
    )
    set_axes_equal(ax, plot_points)

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.legend()
    ax.grid(True)
    fig.tight_layout()

    if save_path is not None:
        fig.savefig(save_path, dpi=150)
        print(f"Saved plot: {save_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def main() -> None:
    args = parse_args()

    reference = load_reference_trajectory(args.ref)
    real, state_timestamps = parse_logged_states(args.log)
    final_point_timestamp = parse_final_point_timestamp(args.log)
    completion_time = compute_completion_time(state_timestamps, final_point_timestamp)
    #real = np.insert(real, 0, reference[0], axis=0)

    mean_diff, max_diff = compute_metrics(reference, real)

    print(f"Reference points: {len(reference)}")
    print(f"Real points: {len(real)}")
    print(f"Avg difference: {mean_diff:.6f}")
    print(f"Max difference: {max_diff:.6f}")
    if completion_time is None:
        print("Path completion time: unavailable")
    else:
        print(f"Path completion time: {completion_time:.3f} s")

    plot_trajectories(
        reference=reference,
        real=real,
        save_path=args.save_plot,
        show=not args.no_show,
    )


if __name__ == "__main__":
    main()
